version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: red
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
